CREATE DATABASE SALESPSPTEST
GO
USE SALESPSPTEST 
GO 
DECLARE @I AS INT=1

CREATE TABLE CUSTOMERS (ID INT IDENTITY(1,1) PRIMARY KEY,CUSTOMERNAME VARCHAR(100))
SET @I=1
DECLARE @CUSTOMERNAME AS VARCHAR(100)
WHILE @I<=1000000
BEGIN
	SET @CUSTOMERNAME='CUSTOMER'+REPLICATE('0',7-LEN(@I))+CONVERT(VARCHAR,@I)
	INSERT INTO CUSTOMERS (CUSTOMERNAME) VALUES (@CUSTOMERNAME)
SET @I=@I+1
END

