CREATE DATABASE SALESPSP
GO
USE SALESPSP 
GO 
CREATE TABLE ITEMS (ID INT IDENTITY(1,1) PRIMARY KEY,ITEMNAME VARCHAR(100),PRICE FLOAT)
DECLARE @I AS INT=1
DECLARE @PRICE AS FLOAT
DECLARE @ITEMNAME AS VARCHAR(100)
WHILE @I<=100
BEGIN
	 
	SET @PRICE =RAND()*10000
	SET @PRICE=ROUND(@PRICE,2)
	SET @ITEMNAME='ITEM'+REPLICATE('0',3-LEN(@I))+CONVERT(VARCHAR,@I)
	INSERT INTO ITEMS (ITEMNAME,PRICE) VALUES (@ITEMNAME,@PRICE )
SET @I=@I+1
END


SELECT * FROM ITEMS 


CREATE TABLE CUSTOMERS (ID INT IDENTITY(1,1) PRIMARY KEY,CUSTOMERNAME VARCHAR(100))
SET @I=1
DECLARE @CUSTOMERNAME AS VARCHAR(100)
WHILE @I<=100
BEGIN
	SET @CUSTOMERNAME='CUSTOMER'+REPLICATE('0',3-LEN(@I))+CONVERT(VARCHAR,@I)
	INSERT INTO CUSTOMERS (CUSTOMERNAME) VALUES (@CUSTOMERNAME)
SET @I=@I+1
END

CREATE TABLE SALES (ID INT IDENTITY(1,1) PRIMARY KEY,ITEMID INT,CUSTOMERID INT,DATE_ DATETIME,AMOUNT INT,PRICE FLOAT,TOTALPRICE FLOAT,DEFINITION_ BINARY(4000))
SET @I=0
DECLARE @ITEMID AS INT

DECLARE @AMOUNT AS INT
DECLARE @CUSTOMERID AS INT
DECLARE @DATE AS DATETIME 

WHILE @I<500000
BEGIN
	DECLARE @RAND AS FLOAT
	SET @RAND =RAND()

	IF @RAND<0.9
		SET @ITEMID =1
	ELSE 
		SET @ITEMID=(RAND()*99)+1

	SELECT @PRICE=PRICE FROM ITEMS WHERE ID=@ITEMID
	SET @CUSTOMERID=(RAND()*99)+1
	DECLARE @DAYCOUNT AS INT
	DECLARE @SECONDCOUNT AS INT
 
	SET @AMOUNT=(RAND()*19)+1
	SET @DAYCOUNT=RAND()*180
	SET @SECONDCOUNT=RAND()*24*60
	SET @DATE=DATEADD(DAY,@DAYCOUNT,GETDATE())
	SET @DATE=DATEADD(DAY,@SECONDCOUNT,@DATE )
	INSERT INTO SALES (ITEMID,CUSTOMERID,AMOUNT,PRICE,TOTALPRICE,DATE_)
	VALUES (@ITEMID,@CUSTOMERID,@AMOUNT,@PRICE,@PRICE*@AMOUNT,@DATE)
SET @I=@I+1
END
CREATE INDEX IX1 ON SALES (ITEMID)

